[package]
name = "rustno"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
gtk = "0.14.1"
relm = "0.22.0"
relm-derive = "0.22.0"
